/**
 * Builds the JSON Schema artifact from the endpoint registry.
 *
 * The artifact is checked in under `generated/` and regenerated by
 * `pnpm --filter @betterwakeup/contract run generate`. A test compares the
 * checked-in file against a fresh build, so a schema change that was not
 * regenerated fails CI rather than reaching a consumer.
 *
 * This module is deliberately not re-exported from the package index. It is a
 * build concern, and nothing in the app or the server should import it.
 */

import { z } from "zod";
import { ENDPOINTS } from "./endpoints.ts";
import { ERROR_DISPOSITIONS, errorResponse } from "./errors.ts";
import { DISCLOSURE_POLICY_VERSION } from "./policy.ts";
import {
  DONATED_SHARE_OF_FORFEIT_PERCENT,
  IDEMPOTENCY_HEADER,
  MAXIMUM_CHALLENGE_DURATION_DAYS,
  MAXIMUM_PAUSE_DAYS,
  MINIMUM_FUNDED_DEPOSIT_MINOR_UNITS,
  RECEIPT_GRACE_SECONDS,
  RECOVERY_WINDOW_HOURS,
} from "./primitives.ts";

/** Path of the checked-in artifact, relative to this package's root. */
export const GENERATED_SCHEMA_PATH = "generated/contract.schema.json";

/**
 * A request is described by what a client may send, and a response by what a
 * client receives, so the two directions of a schema with defaults or
 * transforms do not collapse into one.
 */
function toJsonSchema(schema: z.ZodType, io: "input" | "output"): unknown {
  return z.toJSONSchema(schema, { io, unrepresentable: "any" });
}

export function buildContractJsonSchema(): unknown {
  const endpoints = Object.fromEntries(
    Object.entries(ENDPOINTS).map(([name, endpoint]) => [
      name,
      {
        method: endpoint.method,
        path: endpoint.path,
        auth: endpoint.auth,
        idempotent: endpoint.idempotent,
        params: endpoint.params === null ? null : toJsonSchema(endpoint.params, "input"),
        request: endpoint.request === null ? null : toJsonSchema(endpoint.request, "input"),
        response: toJsonSchema(endpoint.response, "output"),
      },
    ]),
  );

  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "BetterWakeUp API contract",
    headers: {
      idempotency: IDEMPOTENCY_HEADER,
    },
    policy: {
      minimumFundedDepositMinorUnits: MINIMUM_FUNDED_DEPOSIT_MINOR_UNITS,
      maximumChallengeDurationDays: MAXIMUM_CHALLENGE_DURATION_DAYS,
      maximumPauseDays: MAXIMUM_PAUSE_DAYS,
      receiptGraceSeconds: RECEIPT_GRACE_SECONDS,
      recoveryWindowHours: RECOVERY_WINDOW_HOURS,
      donatedShareOfForfeitPercent: DONATED_SHARE_OF_FORFEIT_PERCENT,
      disclosurePolicyVersion: DISCLOSURE_POLICY_VERSION,
    },
    errors: {
      response: toJsonSchema(errorResponse, "output"),
      dispositions: ERROR_DISPOSITIONS,
    },
    endpoints,
  };
}

/** The artifact's exact on-disk text, newline-terminated. */
export function renderContractJsonSchema(): string {
  return `${JSON.stringify(buildContractJsonSchema(), null, 2)}\n`;
}
